ALTER TABLE public.episodes
  ADD COLUMN IF NOT EXISTS mode_admission text CHECK (mode_admission IN ('urgences','programme','transfert','domicile','autre')),
  ADD COLUMN IF NOT EXISTS provenance text,
  ADD COLUMN IF NOT EXISTS ta_systolique integer,
  ADD COLUMN IF NOT EXISTS ta_diastolique integer,
  ADD COLUMN IF NOT EXISTS fc integer,
  ADD COLUMN IF NOT EXISTS fr integer,
  ADD COLUMN IF NOT EXISTS spo2 integer,
  ADD COLUMN IF NOT EXISTS temperature numeric(4,1),
  ADD COLUMN IF NOT EXISTS poids_entree_kg numeric(5,1),
  ADD COLUMN IF NOT EXISTS taille_entree_cm numeric(5,1),
  ADD COLUMN IF NOT EXISTS eva_douleur integer CHECK (eva_douleur BETWEEN 0 AND 10),
  ADD COLUMN IF NOT EXISTS etat_general text,
  ADD COLUMN IF NOT EXISTS autonomie_gir integer CHECK (autonomie_gir BETWEEN 1 AND 6),
  ADD COLUMN IF NOT EXISTS contexte_social text,
  ADD COLUMN IF NOT EXISTS observance_habituelle text CHECK (observance_habituelle IN ('bonne','partielle','mauvaise','inconnue')),
  ADD COLUMN IF NOT EXISTS bmo_sources text[],
  ADD COLUMN IF NOT EXISTS bmo_notes text,
  ADD COLUMN IF NOT EXISTS bilan_entree_completed_at timestamptz;